# Generated by Django 4.1.1 on 2022-10-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('email', models.EmailField(max_length=200, verbose_name='мэйл')),
                ('author', models.TextField(default='', max_length=3000, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('NOT_ACTIVE', 'Не активна')], default='ACTIVE', max_length=100, verbose_name='Статус')),
            ],
        ),
        migrations.DeleteModel(
            name='CW',
        ),
    ]
